version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/
    overwrite: yes

hooks:
  ApplicationStop:
    - location: scripts/kill_old_process.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 120
      runas: root
#    - location: scripts/set_port_forwarding.sh
#      timeout: 60
#      runas: root